name: "CLI for Microsoft 365 Login"
description: "Login to tenant using CLI for Microsoft 365"
inputs:
  ADMIN_USERNAME:
    description: "Username (email address) of the admin"
    required: false
  ADMIN_PASSWORD:
    description: "Password of the admin"
    required: false
  CERTIFICATE_ENCODED:
    description: "Base64-encoded string with certificate private key"
    required: false
  CERTIFICATE_PASSWORD:
    description: "Password for the certificate"
    required: false
  AAD_APP_ID:
    description: "App ID of the Azure AD application to use for certificate authentication"
    required: false
  TENANT_ID:
    description: "ID of the tenant from which accounts should be able to authenticate"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "log-in"  
  color: "blue"